node-honeycomb/honeycomb-server

lib/admin/gather_usage.js, lib/child.js, lib/master.js, lib/run.js
* reload now can adjust processorNum
* support app env config
* support  app --max_old_space_size config
=> fix: app reload support processorNum adjust

Makefile, lib/child.js, lib/master.js, lib/run.js, package.json, test/env.js, test/lib/admin_batch_api.test.js, test/lib/admin_single_api.test.js, test/lib/master.test.js
* 修复测试，支持多进程
* 升级alinode
* 修复服务退出时，释放无用的端口
=> fix: test cov with multi-process

Makefile, lib/child.js, lib/master.js, lib/proxy/nginx.js, lib/proxy/proxy.js, lib/run.js, test/common.js, test/lib/master.test.js
=> fix: nginx config rollback bug

lib/admin/single_api/app.js
-m means 
> don't extract file modified time
=> fix: tar add -m

config/config_default.js, lib/child.js, package.json
=> feat: add a config: forceKillTimeout

config/config_production.js, package.json
=> fix: setup defalut serverRoot when release

config/index.js, lib/proxy/nginx.js, package.json, test/config.test.js, test/lib/proxy/nginx.test.js
* 修复app reload导致请求异常问题，nginx的reload有时延
* 修复配置 reload的内存泄露问题，require.cache 问题
=> Fix app reload and config reload

config/index.js, lib/child.js, package.json
=> fix: child stdout log

lib/proxy/nginx.js, lib/proxy/node.js, lib/proxy/proxy.js, package.json, test/lib/proxy/nginx.test.js
* 当应用变化时，判断路由是否变化，如无变化，则不触发reload
=> Fix no change reload

Makefile, example-apps/exception-retry-app/index.js, example-apps/exception-retry-app/package.json.package.json, lib/child.js, lib/run.js, package.json, test/lib/admin/api_app.test.js
* app exception 支持reload，方便调试
* app状态梳理
=> fix: app status  #71 #53

common/utils.js, test/common/utils.test.js
=> fix: adjust version weight calculation

config/config_default.js, config/index.js, lib/admin/single_api/log.js, lib/child.js, lib/master.js, lib/proxy/nginx.js, lib/proxy/node.js, lib/run.js, package.json
=> fix: stop illegal app bug

example-apps/reload-app_1.0.0_1/index.js, lib/admin/batch_api/system.js, lib/admin/router.js, lib/admin/single_api/system.js, lib/admin/utils.js, lib/child.js, lib/run.js, test/common.js, test/lib/admin/api_app.test.js, test/lib/admin/api_cluster_info.test.js, test/lib/admin/api_log.test.js, test/lib/admin/api_online_offline.test.js, test/lib/admin/api_publish.test.js, test/lib/admin/api_status.test.js, test/lib/admin/app_router.test.js, test/lib/master.test.js
* 新增
clusterInfo接口，方便集群内机器实现广播。
clusterInfo信息还需要console配合。
=> feat: add cluster info api

lib/admin/single_api/system.js
=> fix: memoryUsage calculate bug

config/config_default.js, lib/admin/index.js, lib/admin/utils.js, test/common.js, test/lib/admin/api_other.test.js
batch接口的参数ips，除了支持ip之外，支持endpoint格式，方便现场组装集群。
ips:
```
127.0.0.1
http://127.0.0.1:9999
```
=> feat: batch api support endpoint config

lib/admin/controller.js
=> update timeout to 5 mins

lib/admin/gather_usage.js, lib/admin/single_api/app.js, test/lib/proxy/nginx.test.js
=> fix: single api exec env path

Makefile, example-apps/exenoent-app/package.json, lib/child.js, test/lib/admin/api_publish.test.js
fix spawn exception when exec not found
=> fix: spawn none exists executor cause server exit bug

common/utils.js, example-apps/java-port-app/package.json, lib/child.js, test/common/utils.test.js
避免Java应用，设置了过大的-Xmx和-Xmn等，超过了外部Pod设置的Memory limit，从而容易导致OOM。
不过JDK 10之后，可以使用这几个参数：
-XX:-UseContainerSupport
-XX:InitialRAMPercentage
-XX:MaxRAMPercentage
=> dynamic change application's memory opts for java

package.json
Ref: https://nvd.nist.gov/vuln/detail/CVE-2023-37466
=> fix security issue of vm2

lib/admin/auth.js, package.json
=> remove auth for /api/liveness
